### ISSUE TITLE
Stability Checker logs do not contain actual error logs

### ISSUE THREAD

**Issue by nachtmaar** [kyma-project/test-infra#1597] opened 2019-10-10 11:42 UTC
**Description**

When getting the `stability-checker` logs of e.g. nightly cluster, it is not possible to figure out the actual test-failure. The logs of the test pods are not fetched by `stability-checker`. `ClusterTestSuite` is there, but that only tells you which tests failed/passed.

**Expected result**

I see the logs of a failed test, e.g. for `event-bus` tests.

**Actual result**

**Steps to reproduce**

```
gsutil -m cp -r 'gs://stability-checker-logs/nightly/2019-10/10/*.gz' .
gunzip *
```
E.g. take the log file `201910100130_1`

```
$ cat /private/tmp/nightly/201910100130_1 |jq '.log|fromjson|.log.message'
"Test end with error [start time: 2019-10-10 01:05:48.721963031 +0000 UTC m=+73483.927751735, duration: 26m39.066367653s]"
"----------------------------\n- Testing Kyma...\n----------------------------\nclusteraddonsconfiguration \"testing-addons\" created\nWaiting for ready testing addons 0/10.. status: \nWaiting for ready testing addons 1/10.. status: Pending\n\u001b[32mTesting addons injected\u001b[0m\nclustertestsuite \"testsuite-all-2019-10-10-01-05\" created\nClusterTestSuite not finished. Waiting...\nClusterTestSuite not finished. Waiting...\nClusterTestSuite not finished. Waiting...\nClusterTestSuite not finished. Waiting...\nClusterTestSuite not finished. Waiting...\nClusterTestSuite not finished. Waiting...\nClusterTestSuite not finished. Waiting...\nClusterTestSuite not finished. Waiting...\nClusterTestSuite not finished. Waiting...\nClusterTestSuite not finished. Waiting...\nClusterTestSuite not finished. Waiting...\nClusterTestSuite not finished. Waiting...\nClusterTestSuite not finished. Waiting...\nClusterTestSuite not finished. Waiting...\nClusterTestSuite not finished. Waiting...\nClusterTestSuite not finished. Waiting...\nClusterTestSuite not finished. Waiting...\nClusterTestSuite not finished. Waiting...\nClusterTestSuite not finished. Waiting...\nClusterTestSuite not finished. Waiting...\nClusterTestSuite not finished. Waiting...\nClusterTestSuite not finished. Waiting...\nClusterTestSuite not finished. Waiting...\nClusterTestSuite not finished. Waiting...\nClusterTestSuite not finished. Waiting...\nClusterTestSuite not finished. Waiting...\nClusterTestSuite not finished. Waiting...\nTest suite 'testsuite-all-2019-10-10-01-05' failed.\nTest summary\nTest status: dex-integration - Succeeded\nTest status: event-bus - Failed (Retried)\nTest status: core-kubeless - Succeeded\nTest status: knative-serving - Succeeded\nTest status: dex-connection - Succeeded\nTest status: core-console - Succeeded\nTest status: core - Succeeded\nTest status: connection-token-handler - Succeeded\nTest status: logging - Succeeded\n\u001b[0m\u001b[1mAll test pods should be terminated. Checking...\u001b[0m\n\u001b[32m\u001b[1mOK\u001b[0m\nClusterTestSuite details:\napiVersion: testing.kyma-project.io/v1alpha1\nkind: ClusterTestSuite\nmetadata:\n  annotations:\n    kubectl.kubernetes.io/last-applied-configuration: |\n      {\"apiVersion\":\"testing.kyma-project.io/v1alpha1\",\"kind\":\"ClusterTestSuite\",\"metadata\":{\"annotations\":{},\"labels\":{\"controller-tools.k8s.io\":\"1.0\"},\"name\":\"testsuite-all-2019-10-10-01-05\",\"namespace\":\"\"},\"spec\":{\"concurrency\":1,\"maxRetries\":1}}\n  creationTimestamp: 2019-10-10T01:05:57Z\n  generation: 1\n  labels:\n    controller-tools.k8s.io: \"1.0\"\n  name: testsuite-all-2019-10-10-01-05\n  resourceVersion: \"442890\"\n  selfLink: /apis/testing.kyma-project.io/v1alpha1/clustertestsuites/testsuite-all-2019-10-10-01-05\n  uid: 1da7d8c5-eafa-11e9-913d-42010aa400d1\nspec:\n  concurrency: 1\n  maxRetries: 1\nstatus:\n  completionTime: 2019-10-10T01:32:22Z\n  conditions:\n  - status: \"False\"\n    type: Running\n  - status: \"True\"\n    type: Failed\n  results:\n  - executions:\n    - completionTime: 2019-10-10T01:06:19Z\n      id: oct-tp-testsuite-all-2019-10-10-01-05-dex-integration-0\n      podPhase: Succeeded\n      startTime: 2019-10-10T01:05:58Z\n    name: dex-integration\n    namespace: kyma-system\n    status: Succeeded\n  - executions:\n    - completionTime: 2019-10-10T01:14:33Z\n      id: oct-tp-testsuite-all-2019-10-10-01-05-event-bus-0\n      podPhase: Failed\n      startTime: 2019-10-10T01:06:19Z\n    - completionTime: 2019-10-10T01:22:23Z\n      id: oct-tp-testsuite-all-2019-10-10-01-05-event-bus-1\n      podPhase: Failed\n      startTime: 2019-10-10T01:14:33Z\n    name: event-bus\n    namespace: kyma-system\n    status: Failed\n  - executions:\n    - completionTime: 2019-10-10T01:23:30Z\n      id: oct-tp-testsuite-all-2019-10-10-01-05-core-kubeless-0\n      podPhase: Succeeded\n      startTime: 2019-10-10T01:22:24Z\n    name: core-kubeless\n    namespace: kyma-system\n    status: Succeeded\n  - executions:\n    - completionTime: 2019-10-10T01:24:07Z\n      id: oct-tp-testsuite-all-2019-10-10-01-05-knative-serving-0\n      podPhase: Succeeded\n      startTime: 2019-10-10T01:23:30Z\n    name: knative-serving\n    namespace: knative-serving\n    status: Succeeded\n  - executions:\n    - completionTime: 2019-10-10T01:24:14Z\n      id: oct-tp-testsuite-all-2019-10-10-01-05-dex-connection-0\n      podPhase: Succeeded\n      startTime: 2019-10-10T01:24:08Z\n    name: dex-connection\n    namespace: kyma-system\n    status: Succeeded\n  - disabledConcurrency: true\n    executions:\n    - completionTime: 2019-10-10T01:32:01Z\n      id: oct-tp-testsuite-all-2019-10-10-01-05-core-console-0\n      podPhase: Succeeded\n      startTime: 2019-10-10T01:25:38Z\n    name: core-console\n    namespace: kyma-system\n    status: Succeeded\n  - executions:\n    - completionTime: 2019-10-10T01:25:26Z\n      id: oct-tp-testsuite-all-2019-10-10-01-05-core-0\n      podPhase: Succeeded\n      startTime: 2019-10-10T01:24:14Z\n    name: core\n    namespace: kyma-system\n    status: Succeeded\n  - disabledConcurrency: true\n    executions:\n    - completionTime: 2019-10-10T01:32:22Z\n      id: oct-tp-testsuite-all-2019-10-10-01-05-connection-token-handler-0\n      podPhase: Succeeded\n      startTime: 2019-10-10T01:32:05Z\n    name: connection-token-handler\n    namespace: kyma-integration\n    status: Succeeded\n  - executions:\n    - completionTime: 2019-10-10T01:25:38Z\n      id: oct-tp-testsuite-all-2019-10-10-01-05-logging-0\n      podPhase: Succeeded\n      startTime: 2019-10-10T01:25:26Z\n    name: logging\n    namespace: kyma-system\n    status: Succeeded\n  startTime: 2019-10-10T01:05:57Z\n\u001b[0m\u001b[1mDeleting ClusterTestSuite testsuite-all-2019-10-10-01-05\u001b[0m\n\u001b[32m\u001b[1mOK\u001b[0m\n\u001b[0m\u001b[1mImages with tag latest are not allowed. Checking...\u001b[0m\n\u001b[31meu.gcr.io/kyma-project/xf-application-mocks/commerce-mock:latest\neu.gcr.io/kyma-project/xf-application-mocks/commerce-mock:latest\u001b[0m\n\u001b[31mFAILED\u001b[0m\nclusteraddonsconfiguration \"testing-addons\" deleted\n\u001b[32mTesting addons removed\u001b[0m\nError from server (NotFound): clusteraddonsconfigurations.addons.kyma-project.io \"testing-addons\" not found\n\u001b[32mTesting addons removed\u001b[0m\n"
"Start test"
```
**Troubleshooting**

**Comment by klaudiagrz** [comment] 2019-10-11 09:40
contact person: 
@nachtmaar and @lilitgh

**Comment by nachtmaar** [comment] 2020-01-03 16:46
I reckecked stability-checker logs and the logs of the test pods are still not there. Please correct me if I am wrong. I am reopening the issue for now @PK85.

Tested with logs of nightly cluster at 2020-01-03

I downloaded the logs like this:

```bash
gsutil -m cp -r 'gs://stability-checker-logs/nightly/2020-01/03/*.gz'
gunzip *
cat * | jq '.log|fromjson?|.log.message'
```

I can only see the description of the ClusterTestSuite.

**Comment by polskikiel** [comment] 2020-01-09 12:40
That issue is non-deterministic, sometimes the logs are not present. It may be related to the overloaded k8s API server, which is a cause of stability-checker to not fetch logs.
For example by running: 
```
gsutil -m cp -r 'gs://stability-checker-logs/nightly/2020-01/09/*.gz' .
gunzip *
cat * | jq '.log|fromjson?|.log.message'
```
the logs are available.

The Stability-checker is using the old testing script, which should be changed to KymaCLI: https://github.com/kyma-project/test-infra/issues/1904.

We still need to investigate what is the root cause.

**Comment by ksputo** [comment] 2020-01-29 09:42
FYI:
It seems that testing script currently used by stabillity checker exists [at this point](https://github.com/kyma-project/kyma/blob/45f07c16478884025df501c576b76f95e24ed02d/installation/scripts/testing-common.sh#L44-L50).

As you can see in the logs:
a) case when logs are printed
```
Test suite 'testsuite-all-2020-01-26-23-29' failed.
Test summary
Test status: application-operator - Succeeded
Test status: application-registry - Succeeded
Test status: core-cluster-users - Succeeded
Test status: connector-service - Succeeded
Test status: rafter - Succeeded
Test status: core-api-controller - Succeeded
Test status: kiali - Succeeded
Test status: core-console - Succeeded
Test status: application-connector - Succeeded
Test status: core-test-external-solution - Failed (Retried)
Test status: core-kubeless - Succeeded
Test status: monitoring - Succeeded
Test status: connection-token-handler - Succeeded
Test status: logging - Succeeded
Test status: dex-integration - Succeeded
Test status: core-console-backend-service - Failed (Retried)
Test status: e2e-kubeless - Succeeded
Test status: core-apiserver-proxy - Succeeded
Test status: knative-serving - Succeeded
Test status: api-gateway - Succeeded
Test status: service-catalog - Succeeded
Test status: dex-connection - Succeeded
Test status: event-bus - Succeeded
\\u001b[0m\\u001b[1mAll test pods should be terminated. Checking...\\u001b[0m
\\u001b[32m\\u001b[1mOK\\u001b[0m
ClusterTestSuite details:
```
case when logs **are not printed**
```
Timeout for test suite 'testsuite-all-2020-01-09-02-31' occurred.
Test summary
Test status: application-operator - Succeeded
Test status: connector-service - Succeeded
Test status: core-test-external-solution - Failed (Retried)
Test status: kiali - Succeeded
Test status: connection-token-handler - Succeeded
Test status: core-apiserver-proxy - Succeeded
Test status: rafter - Succeeded
Test status: service-catalog - Succeeded
Test status: api-gateway - Succeeded
Test status: core-api-controller - Succeeded
Test status: core-cluster-users - Succeeded
Test status: dex-connection - Succeeded
Test status: e2e-kubeless - Failed (Retried)
Test status: logging - Succeeded
Test status: event-bus - Succeeded
Test status: monitoring - Succeeded
Test status: knative-serving - Succeeded
Test status: application-connector - Succeeded
Test status: application-registry - Succeeded
Test status: core-console-backend-service - Running (Retried)
Test status: core-kubeless - Succeeded
Test status: dex-integration - Succeeded
\\u001b[0m\\u001b[1mAll test pods should be terminated. Checking...\\u001b[0m
\\u001b[31mTest pod 'oct-tp-testsuite-all-2020-01-09-02-31-core-console-backend-service-1' has not terminated, pod phase: Running\\u001b[0m
Waiting for test pods to terminate...
\\u001b[31mTest pod 'oct-tp-testsuite-all-2020-01-09-02-31-core-console-backend-service-1' has not terminated, pod phase: Running\\u001b[0m
Waiting for test pods to terminate...
\\u001b[31mTest pod 'oct-tp-testsuite-all-2020-01-09-02-31-core-console-backend-service-1' has not terminated, pod phase: Running\\u001b[0m
Waiting for test pods to terminate...
\\u001b[31mFAILED\\u001b[0m
\\u001b[0m\\u001b[1mTesting 'oct-tp-testsuite-all-2020-01-09-02-31-core-console-backend-service-1' from namespace 'kyma-system'\\u001b[0m
\\u001b[31m'oct-tp-testsuite-all-2020-01-09-02-31-core-console-backend-service-1' failed due to too long Running status\\u001b[0m
\\u001b[0m\\u001b[1mFetching logs from 'oct-tp-testsuite-all-2020-01-09-02-31-core-console-backend-service-1' with options tailLimit=2000 and bytesLimit=500000\\u001b[0m
```

In case a) pods which failed are terminated which blocks the script from fetching logs - cause the script exists on step mentioned before and therefore never actually runs command _kubectl logs_
- there is no point adjusting this script as it is deprecated. As @polskikiel said, we need to change it to Kyma CLI. Will do it as soon as we are done with other, higher priority stories.

**Comment by ksputo** [comment] 2020-01-29 09:43
Currently blocked by #1904

**Comment by polskikiel** [comment] 2020-05-25 12:12
It will be fixed within this issue: https://github.com/kyma-project/test-infra/issues/1904

**Closed by polskikiel** 2020-05-25 12:12 UTC
Labels: bug
