### ISSUE TITLE
Prepare Prow job for testing connection of the Kyma Runtime to the Central Kyma

### ISSUE THREAD

**Issue by Szymongib** [kyma-project/test-infra#1160] opened 2019-06-19 09:24 UTC
**Description**

Test for connection of the Kyma Runtime to the Central Kyma should be run on the release branch to verify that it is working correctly.

The Prow job should be required as this is one of the critical functionalities.

**Reasons**

The functionality must work on every release.

**Related Issues**
https://github.com/kyma-project/kyma/issues/4592

**Comment by janmedrek** [comment] 2020-01-02 10:40
Duplicate of #4592

**Closed** 2020-01-02 10:40 UTC
Labels: area/application-connector, duplicate, enhancement
