### ISSUE TITLE
Image syncer support for multiple external-images.yaml files

### ISSUE THREAD

**Issue by dekiel** [kyma-project/test-infra#11184] opened 2024-07-01 10:41 UTC
The image syncer tool should support multiple files with definition which images to sync. At present the tool is reading this data from one file external-images.yaml. Because the file is shared between all teams, a neighbors team is a codeowner of the file. We review and accept changes in the file even when the change doesn't relate to our work. Having support for multiple files, each team could have it's own file and maintain it's content. This way Neighbors team will not review changes which are not related to our work and we don't have required knowledge about the change. Additionally having CODEOWNERS entries for each file, it will be documented which team owns synced images.

We might consider adding support for external-imges.yaml files hosted in other teams repositories. This would be even more convienient for the teams. The problem might be to work with duplicated images to sync.

**ACCEPTANCE CRITERIA**
- [ ] Image syncer support multiple external-images.yaml files.
- [ ] CODEOWNERS file has entry for each file.
- [ ] Files are stored under repository global /configs directory.

**Comment by Sawthis** [comment] 2024-08-20 10:37
duplicate of https://github.com/kyma-project/test-infra/issues/11384

**Closed by Sawthis** 2024-08-20 10:37 UTC
Labels: kind/feature, area/automation
