### ISSUE TITLE
image-builder: sign images with signify

### ISSUE THREAD

**Issue by Ressetkk** [kyma-project/test-infra#6057] opened 2022-09-22 12:51 UTC
As it's a requirement for SLC-29 we have to implement image signing using signify in image-builder.

The tool should get *all* image tags that have been built in `postsubmit` mode, make specific request to signify, and return specific information about that.

/area ci
/kind feature

**Comment by Ressetkk** [comment] 2022-09-26 14:55
This feature seems to be pretty straightforward. We have access to the signify through an URL. The signing is performed by making a `POST` request to the `/sign` endpoint of signing service. The request body should contain the following array:
```
[{
notaryGun string # URL of the image in registry
sha256 string # digest of the image
byteSize int # image size
version string # image tag to be signed
}]
```
As far as I understand the signing of multiple tags is performed by adding another JSON Object with different `version` to the array. We get the information which images have been published with specific tags when the job finishes. Once the job finishes with success, we can gather the information, build a payload and make a request to the notary server with built-in http client. Authorization is made by simple JWT token.

@TorstenD-SAP please, cen you provide some insights if my understanding is correct?

**Comment by dekiel** [comment] 2022-10-04 09:38
In case a signing of image failed will we remove the image from registry? If we don't remove the image then all usage of it must validate signature. The behaviour of image-builder must be documented.

At present such usage would be a release. I don't know any other usage for now.

**Comment by Ressetkk** [comment] 2022-10-04 10:30
On-cluster image validation would be required. If image doesn't have the signature, simply, the verification will fail. Such edge-cases should be caught with provisioning tests. No need to handle it during signing.

For signing I see no problem with implementing sign retry in case of failure.

**Comment by dekiel** [comment] 2022-10-05 08:43
We should add some retry logic for signing for sure.

Agree, for the scenario of deploying image on cluster validation is required and as far I know that's the next step.

I was rather thinking about other usages of this image. Something like releasing image or promoting it to the first release channel. If the process of releasing will be independent from image building it must validate the signature as well to not release image which is in production registry but doesn't have a signature. If we will not remove such image from registry we potentially will have a mix of images with and without signature. I think for release we should be safe even if signing fail and we got such image in registry. Because before the image will be available in release channel it will have to pass some checks and I expect a signature check will be one of it.

The question is if that is the only scenario/usage we should eventually think about.

If we decide to not remove images for which signing failed, we must document that and communicate to other teams. We should check as well if SLC-29 or requirements from C4J describe expected behaviour.

**Comment by tobiscr** [comment] 2022-10-20 09:07
Counter part on Kyma-cluster side is this [issue](https://github.tools.sap/kyma/backlog/issues/3095)

**Closed** 2022-10-27 09:09 UTC
Labels: area/ci, kind/feature
