### ISSUE TITLE
Improve changelog generator

### ISSUE THREAD

**Issue by adamwalach** [kyma-project/test-infra#4312] opened 2021-10-14 17:33 UTC
**Description**

Current implementation of [change log generator](https://github.com/kyma-project/test-infra/tree/main/changelog-generator) ignores PRs that do not have `area/` label. 
That causes a lot of miscommunication when a given functionality or fix is not presented on Kyma release.

Possible solutions:
- have a common section in changelog for PRs without label 
- set a default label on every PR. Possibly something that draws attention like `area/FIX_THIS_LABEL` and makes everyone aware that they need to do something about it

**Comment by Ressetkk** [comment] 2022-01-27 16:22
Maybe we should use `release-note` plugin from Prow?


>The release-note plugin implements a release note process that uses a markdown 'release-note' code block to associate a release note with a pull request. Until the 'release-note' block in the pull request body is populated the PR will be assigned the 'do-not-merge/release-note-label-needed' label. 
There are three valid types of release notes that can replace this label:
PRs with a normal release note in the 'release-note' block are given the label 'release-note'.
PRs that have a release note of 'none' in the block are given the label 'release-note-none' to indicate that the PR does not warrant a release note.
PRs that contain 'action required' in their 'release-note' block are given the label 'release-note-action-required' to indicate that the PR introduces potentially breaking changes that necessitate user action before upgrading to the release.
To use the plugin, in the pull request body text: ```release-note ```

**Comment by dekiel** [comment] 2022-01-31 15:13
We need some solution which will require explicit providing release note or skiping a commit/pr from including in release notes. This way we will solve issues caused by developers forget add release note.

**Comment by Ressetkk** [comment] 2022-02-15 10:38
After some brainstorming that we had internally I've come up with a list of improvements that should be done to the changelog-generator:

* [ ] Store changelogs inside target repository
* [ ] Generate changes based on `kind/` label.
* [ ] Run the changelog generation in dedicated pipeline
* [ ] Add the ability to define release notes that will be defined at the top of the changelog. Possibly using markdown block type `release-note` - changelog generator will then pick the text from the block and add a note to the *Notes* section of the changelog.
* [ ] When doing a release Instead of embedding the changelog in the release description add static information `See CHANGELOG for changes.` or something similar.

CHANGELOGs will be stored and updated on main branch. With that said, we will be able to create automation that will automatically update the file with additional changes once the tag is pushed/release is created on the repo.

**Comment by dekiel** [comment] 2022-02-18 09:19
Why we will store changelogs on main? Can we store changelog for a version in a release branch? Having all changelogs in main will require maintaining multiple files.

I would have two additional items added to the list.
- [ ] Changelog and release notes can be reviewed and amended before release is created. Because they will be stored in github, all interested parties will have access to reivew. Changes will be implemented through pull requests.
- [ ] After preparing changelog and release notes we will send notification to release slack channel.

**Comment by Ressetkk** [comment] 2022-02-18 09:38
> Why we will store changelogs on main? Can we store changelog for a version in a release branch? Having all changelogs in main will require maintaining multiple files.
> 
> I would have two additional items added to the list.
> 
> * [ ]  Changelog and release notes can be reviewed and amended before release is created. Because they will be stored in github, all interested parties will have access to reivew. Changes will be implemented through pull requests.
> * [ ]  After preparing changelog and release notes we will send notification to release slack channel.

@dekiel because it'd be pretty hard to maintain them if they are all over the repo. Before pushing a tag there won't be any information about to which version you are going. My idea goes roughly as follows:
* Tag is created.
* Changelog generator generates changelog based on the entire minor release notes in postsubmit prowjob 
* Job raises PR, or automatically commits new changelog to the main branch
* In the release note there is a link to the generated changelog on main branch.

**Comment by dekiel** [comment] 2022-02-18 10:31
Why not raise PR and commit changelog to the release branch? This branch is not removed after release.
In the relase note link to the changelog in release branch.

Can you share some examples why you think this will be hard to maintain? Once we release the changelog will not change. The link on a release will not change.

How we will keep changelogs for different releases in main branch?

**Comment by Ressetkk** [comment] 2022-02-18 11:53
@dekiel
As I said, by the time of creating a tag you have no information which version will be released, especially if we deprecate VERSION file.

Having one place that stores all changelogs regardless the tags which were made will be more convenient and for that we can use the default branch of the repo. Each changelog file can be stored as `CHANGELOG-major.minor.md` and will contain all changes across all tags in minor release. Once a new patch tag will be created then said file will be regenerated. If having branch always one commit ahead after the release I see no problem with storing them additionally on the release branch. It should be possible to sync 2 files across 2 branches.

**Comment by dekiel** [comment] 2022-02-18 12:03
What tag we will be creating if we don't know the the version? Till now our tags represent the release or prerelease version.

**Comment by Ressetkk** [comment] 2022-02-18 13:23
That's exactly my question - How are we going to get the information about the upcoming version if there will be no version defined on the repo before actual release?

Automation is needed that will generate a changelog when the release is created. Be it a ProwJob that triggers when tag is pushed, or else. Then said automation would update the CHANGELOG-major.minor.md file accordingly to the changes between the current and previous tag.

Let's take for example [One of the release branched on Kubernetes repo](https://github.com/kubernetes/kubernetes/commits/release-1.22). There is a bot [k8s-release-robot](https://github.com/kubernetes/kubernetes/commits?author=k8s-release-robot) that creates a release commit, makes a release and after making the release updates the changelog on the release branch AND on default branch. The version in changelog is defined based on pushed tag to the repo.

As for the review before the actual release - Idk. I would see it as optional step when doing a release because version is actually something that has to be manually provided by a person responsible for making a release. Unless you see other approach to that topic.

**Comment by dekiel** [comment] 2022-02-18 13:28
Let's leave this tag for a while. Before you can release a new version you need to create test cluster and make some tests against it. Do you need to know a release version before that can happen?

**Comment by Ressetkk** [comment] 2022-02-18 15:03
For current OSS Kyma version it is not needed, because you can easily install Kyma using local sources and Kyma CLI at any time.

*But* we have an automation which creates release cluster after the release is made. That uses latest released artifacts.

**Comment by Ressetkk** [comment] 2022-05-13 08:48
It's still relevant until we decide on final approach.

/reopen
/remove-lifecycle rotten
/lifecycle frozen

**Comment by Sawthis** [comment] 2022-09-13 07:45
We should focus on generating changelog for micro-deliveres when deployment is made on production: https://github.com/kyma-project/test-infra/issues/5951 . It can be connected with https://github.tools.sap/kyma/backlog/issues/1533#issuecomment-1163466 and: https://github.tools.sap/kyma/backlog/issues/2816

**Comment by dekiel** [comment] 2022-09-26 15:18
Closing in favor of #5951.

**Closed by dekiel** 2022-09-26 15:18 UTC
Labels: area/ci, kind/feature, lifecycle/frozen
