### ISSUE TITLE
Fix the Gardener Azure upgrade job

### ISSUE THREAD

**Issue by marcobebway** [kyma-project/test-infra#2856] opened 2020-10-13 15:13 UTC
**Description**

The [Gardener Azure upgrade job](https://status.build.kyma-project.io/?job=kyma-upgrade-gardener-azure) is failing for some time.

**Expected result**

Job finishes successfully.

**Actual result**

Job failed.

**Steps to reproduce**

Trigger the job.

**Troubleshooting**

```
#################################################################################################
# Create integration-test resources
#################################################################################################

Tue Oct 13 01:41:25 UTC 2020
NAME: integration-test
LAST DEPLOYED: Tue Oct 13 01:41:25 2020
NAMESPACE: integration-test
STATUS: deployed
REVISION: 1
TEST SUITE: None
All pods in e2e-upgrade-test namespace have succeeded phase
Logs for prepare data operation to e2e-upgrade-test: 
error: expected 'logs [-f] [-p] (POD | TYPE/NAME) [-c CONTAINER]'.
POD or TYPE/NAME is a required argument for the logs command
See 'kubectl logs -h' for help and examples
```

**Comment by k15r** [comment] 2020-11-03 11:49
see also: https://github.com/kyma-project/kyma/issues/8964

**Comment by k15r** [comment] 2020-11-23 12:59
Closing as this is a duplicate of kyma-project/kyma#8964

**Closed by k15r** 2020-11-23 12:59 UTC
Labels: area/ci, bug, test-failing
